#!/bin/sh
# angou bootstrap installer.
#
# This script is plaintext and you are about to run it. Read it first: it is
# short, and it is the one part of the store that is not protected by anything.
# Its digest is recorded inside the encrypted store, so a machine that already
# has a trusted angou can detect tampering with `angou verify-bootstrap` — but
# that does not help the first machine, and no arrangement of this file could.
# The published repository is the out-of-band place to check it against.
#
# It touches the network never. Its only inputs are the directory it lives in
# and, later, your recovery passphrase.
#
# Generated by `angou release`. Do not edit: the digest recorded in the store
# will stop matching.

set -eu

RELEASE_KEY_FINGERPRINT="__RELEASE_KEY_FINGERPRINT__"

STORE_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
BOOTSTRAP_DIR="$STORE_DIR/bootstrap"
INSTALL_DIR="${ANGOU_INSTALL_DIR:-$HOME/.local/bin}"

die() {
    printf 'bootstrap: %s\n' "$*" >&2
    exit 1
}

note() {
    printf 'bootstrap: %s\n' "$*" >&2
}

# --- platform -------------------------------------------------------------

detect_platform() {
    os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    arch="$(uname -m)"
    case "$arch" in
        x86_64 | amd64) arch=amd64 ;;
        aarch64 | arm64) arch=arm64 ;;
        *) die "unsupported architecture: $arch" ;;
    esac
    case "$os" in
        linux | darwin) ;;
        *) die "unsupported operating system: $os" ;;
    esac
    printf '%s-%s' "$os" "$arch"
}

available_platforms() {
    for path in "$BOOTSTRAP_DIR"/angou-*; do
        [ -f "$path" ] || continue
        name="$(basename "$path")"
        case "$name" in
            *.sig | *.json) continue ;;
            # The store may also carry the desktop GUI. It is not what a bare
            # machine is recovered with -- it needs CGO, OpenGL and a display
            # server -- and its name starts with the same prefix, so without
            # this it would be read as a CLI build for the platform "gui".
            angou-gui-*) continue ;;
        esac
        printf '%s\n' "$name" |
            sed -n 's/^angou-\([a-z]*\)-\([a-z0-9]*\)-.*$/\1\/\2/p'
    done | sort -u
}

# Picks the highest version present for a platform. This is deliberately
# "newest available" rather than a check against the store's recorded version
# floor: the floor lives inside the encrypted store, and this script has no key.
# An attacker who deletes the newer binaries can still get an older signed one
# installed here, which is why `angou bootstrap` re-checks the real floor once it
# can read it, and refuses to proceed on a stale binary.
#
# The ordering has to agree with the one angou itself uses, and `sort -V` does
# not: it ranks 0.1.0-dev above 0.1.0, where angou treats a pre-release as older
# than the release it leads to. BSD sort, on macOS, has no -V at all. So the
# comparison is done here, in POSIX shell, rather than delegated.

# version_gt A B -> 0 when A is strictly newer than B.
# Numeric components are compared as numbers, and a version carrying a
# pre-release suffix ranks below the same version without one.
version_gt() {
    a_num="${1%%-*}"
    b_num="${2%%-*}"
    case "$1" in *-*) a_pre="${1#*-}" ;; *) a_pre="" ;; esac
    case "$2" in *-*) b_pre="${2#*-}" ;; *) b_pre="" ;; esac

    i=1
    while [ "$i" -le 4 ]; do
        a_part="$(printf '%s' "$a_num" | cut -d. -f"$i")"
        b_part="$(printf '%s' "$b_num" | cut -d. -f"$i")"
        [ -n "$a_part" ] || a_part=0
        [ -n "$b_part" ] || b_part=0
        # A non-numeric component makes the comparison meaningless; treat it as 0.
        case "$a_part" in *[!0-9]*) a_part=0 ;; esac
        case "$b_part" in *[!0-9]*) b_part=0 ;; esac
        [ "$a_part" -gt "$b_part" ] && return 0
        [ "$a_part" -lt "$b_part" ] && return 1
        i=$((i + 1))
    done

    # Equal numerically: a release outranks the same version's pre-release.
    if [ -z "$a_pre" ] && [ -n "$b_pre" ]; then return 0; fi
    if [ -n "$a_pre" ] && [ -z "$b_pre" ]; then return 1; fi
    # Both carry a pre-release suffix: order them lexicographically. POSIX sh
    # has no defined string-greater-than operator, so this asks sort instead.
    [ "$a_pre" != "$b_pre" ] &&
        [ "$(printf '%s\n%s\n' "$a_pre" "$b_pre" | sort | head -n 1)" = "$b_pre" ]
}

newest_binary() {
    best_name=""
    best_version=""
    for path in "$BOOTSTRAP_DIR"/angou-"$1"-*; do
        [ -f "$path" ] || continue
        name="$(basename "$path")"
        case "$name" in
            *.sig | *.json) continue ;;
            angou-gui-*) continue ;;
        esac
        version="${name#angou-"$1"-}"
        if [ -z "$best_name" ] || version_gt "$version" "$best_version"; then
            best_name="$name"
            best_version="$version"
        fi
    done
    printf '%s' "$best_name"
}

# --- dependencies ---------------------------------------------------------

gpg_install_hint() {
    if [ -f /etc/arch-release ]; then
        printf 'pacman -S gnupg'
    elif [ -f /etc/debian_version ]; then
        printf 'apt install gnupg'
    elif [ -f /etc/fedora-release ]; then
        printf 'dnf install gnupg2'
    elif [ "$(uname -s)" = "Darwin" ]; then
        printf 'brew install gnupg'
    else
        printf 'install gnupg with your package manager'
    fi
}

require_gpg() {
    if command -v gpg >/dev/null 2>&1; then
        GPG=gpg
    elif command -v gpg2 >/dev/null 2>&1; then
        GPG=gpg2
    else
        note "gpg is not installed, and it is needed to check the signature on the"
        note "binary before running it. Install it and run this again:"
        note ""
        note "    $(gpg_install_hint)"
        exit 1
    fi
}

# --- verification ---------------------------------------------------------

# Verifies the detached signature and, separately, that the key which made it is
# the one pinned in this file. Verification alone would only establish that some
# key in the imported ring signed the binary, which is not the question.
# Returns 0 when the file verifies against the pinned release key, 1 otherwise.
# The fingerprint is checked separately from the signature: verification alone
# would only establish that some key in the imported ring signed the file, which
# is not the question being asked.
verify_signature() {
    file="$1"
    signature="$2"
    key="$BOOTSTRAP_DIR/release-key.asc"

    [ -f "$signature" ] || return 1
    [ -f "$key" ] || return 1
    [ -n "$RELEASE_KEY_FINGERPRINT" ] || return 1

    gnupghome="$(mktemp -d)"
    chmod 700 "$gnupghome"

    result=1
    if GNUPGHOME="$gnupghome" "$GPG" --batch --quiet --import "$key" 2>/dev/null; then
        status="$gnupghome/status"
        if GNUPGHOME="$gnupghome" "$GPG" --batch --status-file "$status" \
            --verify "$signature" "$file" 2>/dev/null; then
            if grep -q "VALIDSIG $RELEASE_KEY_FINGERPRINT" "$status"; then
                result=0
            fi
        fi
    fi

    rm -rf "$gnupghome"
    return "$result"
}

newest_gui() {
    best_name=""
    best_version=""
    for path in "$BOOTSTRAP_DIR"/angou-gui-"$1"-*; do
        [ -f "$path" ] || continue
        name="$(basename "$path")"
        case "$name" in
            *.sig | *.json) continue ;;
        esac
        version="${name#angou-gui-"$1"-}"
        if [ -z "$best_name" ] || version_gt "$version" "$best_version"; then
            best_name="$name"
            best_version="$version"
        fi
    done
    printf '%s' "$best_name"
}

verify_binary() {
    binary="$1"
    key="$BOOTSTRAP_DIR/release-key.asc"

    [ -f "$binary.sig" ] || die "no signature beside $(basename "$binary"); refusing to install it"
    [ -f "$key" ] || die "no release-key.asc in $BOOTSTRAP_DIR; refusing to install an unverifiable binary"
    [ -n "$RELEASE_KEY_FINGERPRINT" ] ||
        die "this installer has no release key fingerprint pinned, so it cannot tell a genuine binary from a substituted one"

    verify_signature "$binary" "$binary.sig" ||
        die "$(basename "$binary") is not signed by the release key this installer trusts ($RELEASE_KEY_FINGERPRINT); refusing to install it"
}

# --- main -----------------------------------------------------------------

[ -d "$BOOTSTRAP_DIR" ] || die "no bootstrap directory in $STORE_DIR; is this an angou store?"

platform="$(detect_platform)"
binary_name="$(newest_binary "$platform")"

if [ -z "$binary_name" ]; then
    note "this store holds no binary for $platform."
    note "available platforms:"
    available_platforms | while read -r p; do note "    $p"; done
    exit 1
fi

binary="$BOOTSTRAP_DIR/$binary_name"

require_gpg
# No passphrase is asked for here and none is needed: the binary is not
# encrypted. Only its signature is checked.
verify_binary "$binary"

mkdir -p "$INSTALL_DIR"
install -m 755 "$binary" "$INSTALL_DIR/angou"
note "installed $binary_name to $INSTALL_DIR/angou"

# The desktop GUI, when the store carries one for this platform.
#
# Strictly a bonus. Recovery is the CLI's job and has already happened by this
# point, so nothing below may fail the install: a store with no GUI for this
# platform is the normal case, not an error. The GUI also cannot be
# cross-compiled, so a store carries it for fewer platforms than the CLI.
gui_name="$(newest_gui "$platform")"
if [ -n "$gui_name" ]; then
    gui="$BOOTSTRAP_DIR/$gui_name"
    # Verified to the same standard as the CLI. A binary installed from a store
    # is a binary that will run on this machine, and being optional does not
    # make it exempt.
    verify_binary "$gui"
    install -m 755 "$gui" "$INSTALL_DIR/angou-gui"
    note "installed $gui_name to $INSTALL_DIR/angou-gui"

    # A desktop entry, so the GUI is launchable from a menu rather than only by
    # name. The basename must match the Wayland app_id angou-gui sets from its
    # application ID, or the taskbar shows a generic icon and no name.
    apps="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
    if mkdir -p "$apps" 2>/dev/null; then
        cat > "$apps/io.ushineko.angou.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=angou
GenericName=Encrypted file store
Comment=Encrypt sensitive files into a portable, syncable store
Exec=$INSTALL_DIR/angou-gui
Icon=angou
Terminal=false
Categories=Utility;Security;
StartupNotify=true
StartupWMClass=io.ushineko.angou
DESKTOP
        note "wrote a desktop entry to $apps/io.ushineko.angou.desktop"
    fi

    # The icon, so the entry above resolves to something rather than a generic
    # placeholder. Its name must match the Icon= key.
    icons="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/scalable/apps"
    if mkdir -p "$icons" 2>/dev/null; then
        cat > "$icons/angou.svg" <<'ICON'
__ANGOU_ICON_SVG__
ICON
        note "wrote the icon to $icons/angou.svg"
    fi

    # Refresh the desktop's caches where the tools exist. Absent on a bare
    # machine, which is the case this whole script is for, so their absence is
    # not worth mentioning.
    command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$apps" 2>/dev/null
    command -v gtk-update-icon-cache >/dev/null 2>&1 &&
        gtk-update-icon-cache -f -t "${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor" 2>/dev/null
    true
else
    note "this store carries no desktop GUI for $platform; the CLI does everything it does"
fi

case ":$PATH:" in
    *":$INSTALL_DIR:"*) ;;
    *) note "warning: $INSTALL_DIR is not on your PATH; add it to run angou by name" ;;
esac

# Post-install self-check (R5.8.2).
#
# This verifies this script against its own detached signature, made by the same
# offline release key that signed the binary. It cannot use the digest recorded
# inside the store: that record is encrypted, reading it needs the recovery
# passphrase, and nothing should ask for a passphrase at this point.
#
# It is detection after execution, not prevention. A deliberately subverted
# script would simply delete these lines, and this one has already run by the
# time you read its result. What it catches is a script that was altered without
# the release key: accidental drift from a sync conflict or a truncated file, and
# tampering by anyone who has write access to the store but not the offline key.
if [ -f "$0.sig" ]; then
    if verify_signature "$0" "$0.sig"; then
        note "this installer matches its signature."
    else
        note ""
        note "WARNING: this installer does not match its signature."
        note "WARNING: this check ran after the installer did, so it does not tell you the"
        note "WARNING: script you just ran was genuine. It tells you something changed."
        note "WARNING: Treat this machine as suspect and check the script against the"
        note "WARNING: published repository before trusting it."
        exit 1
    fi
else
    note "note: this installer carries no signature, so it could not be self-checked."
fi

note ""
note "Next: angou bootstrap --store $STORE_DIR"
note "That asks for your recovery passphrase and sets this machine up to open the store."
