# angou bootstrap installer for Windows.
#
# This script is plaintext and you are about to run it. Read it first: it is
# short, and it is the one part of the store that is not protected by anything.
# Its digest is recorded inside the encrypted store, so a machine that already
# has a trusted angou can detect tampering with `angou verify-bootstrap` -- but
# that does not help the first machine, and no arrangement of this file could.
# The published repository is the out-of-band place to check it against.
#
# It touches the network never. Its only inputs are the directory it lives in
# and, later, your recovery passphrase.
#
# Run it with:
#     powershell -NoProfile -ExecutionPolicy Bypass -File <store>\bootstrap.ps1
#
# Generated by `angou release`. Do not edit: the digest recorded in the store
# will stop matching. This file is kept to ASCII on purpose: Windows PowerShell
# 5.1 reads a script without a byte-order mark in the ANSI code page.

Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'

$ReleaseKeyFingerprint = '__RELEASE_KEY_FINGERPRINT__'

$StoreDir = $PSScriptRoot
$BootstrapDir = Join-Path $StoreDir 'bootstrap'
if ($env:ANGOU_INSTALL_DIR) {
    $InstallDir = $env:ANGOU_INSTALL_DIR
} else {
    $InstallDir = Join-Path $env:LOCALAPPDATA 'Programs\angou'
}

function Write-Note([string]$Message) {
    [Console]::Error.WriteLine("bootstrap: $Message")
}

function Stop-Bootstrap([string]$Message) {
    Write-Note $Message
    exit 1
}

# --- platform -------------------------------------------------------------

function Get-Platform {
    # A 32-bit PowerShell on 64-bit Windows reports x86 here and the real
    # architecture in PROCESSOR_ARCHITEW6432.
    $arch = $env:PROCESSOR_ARCHITEW6432
    if (-not $arch) { $arch = $env:PROCESSOR_ARCHITECTURE }
    switch ($arch) {
        'AMD64' { return 'windows-amd64' }
        'ARM64' { return 'windows-arm64' }
        default { Stop-Bootstrap "unsupported architecture: $arch" }
    }
}

# Every stashed binary of one kind, by platform. The GUI shares the CLI's
# "angou-" prefix, so it is excluded by name rather than by pattern.
function Get-Stashed([string]$Kind) {
    if (-not (Test-Path -LiteralPath $BootstrapDir -PathType Container)) { return @() }
    $all = Get-ChildItem -LiteralPath $BootstrapDir -File | Where-Object {
        $_.Name -like "$Kind-*" -and $_.Extension -ne '.sig' -and $_.Extension -ne '.json'
    }
    if ($Kind -eq 'angou') {
        $all = $all | Where-Object { $_.Name -notlike 'angou-gui-*' }
    }
    return @($all)
}

function Get-AvailablePlatforms {
    Get-Stashed 'angou' | ForEach-Object {
        if ($_.Name -match '^angou-([a-z]+)-([a-z0-9]+)-') { "$($Matches[1])/$($Matches[2])" }
    } | Sort-Object -Unique
}

# Picks the highest version present for a platform. This is deliberately
# "newest available" rather than a check against the store's recorded version
# floor: the floor lives inside the encrypted store, and this script has no key.
# An attacker who deletes the newer binaries can still get an older signed one
# installed here, which is why `angou bootstrap` re-checks the real floor once
# it can read it, and refuses to proceed on a stale binary.
#
# The ordering agrees with angou's own and with bootstrap.sh's: numeric parts
# compare as numbers, and a pre-release ranks below the release it leads to.
function Get-VersionPart([string]$Number, [int]$Index) {
    $parts = $Number.Split('.')
    if ($Index -ge $parts.Length) { return [long]0 }
    if ($parts[$Index] -notmatch '^[0-9]+$') { return [long]0 }
    return [long]$parts[$Index]
}

function Test-VersionGreater([string]$A, [string]$B) {
    $aNum, $aPre = $A, ''
    $bNum, $bPre = $B, ''
    $i = $A.IndexOf('-'); if ($i -ge 0) { $aNum = $A.Substring(0, $i); $aPre = $A.Substring($i + 1) }
    $i = $B.IndexOf('-'); if ($i -ge 0) { $bNum = $B.Substring(0, $i); $bPre = $B.Substring($i + 1) }
    for ($n = 0; $n -lt 4; $n++) {
        $ap = Get-VersionPart $aNum $n
        $bp = Get-VersionPart $bNum $n
        if ($ap -gt $bp) { return $true }
        if ($ap -lt $bp) { return $false }
    }
    if ($aPre -eq '' -and $bPre -ne '') { return $true }
    if ($aPre -ne '' -and $bPre -eq '') { return $false }
    return ([string]::CompareOrdinal($aPre, $bPre) -gt 0)
}

function Get-Newest([string]$Kind, [string]$Platform) {
    $prefix = "$Kind-$Platform-"
    $bestName = ''
    $bestVersion = ''
    foreach ($f in (Get-Stashed $Kind)) {
        if (-not $f.Name.StartsWith($prefix)) { continue }
        $version = $f.Name.Substring($prefix.Length)
        if ($bestName -eq '' -or (Test-VersionGreater $version $bestVersion)) {
            $bestName = $f.Name
            $bestVersion = $version
        }
    }
    return $bestName
}

# --- dependencies ---------------------------------------------------------

# gpg on PATH, or where Gpg4win or Git for Windows put it. Git for Windows
# ships an MSYS build of gpg that reads paths the POSIX way, which is handled
# below rather than ruled out: on a developer's machine it is often the only
# gpg there is.
function Find-Gpg {
    foreach ($name in 'gpg', 'gpg2') {
        $cmd = Get-Command $name -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($cmd) { return $cmd.Source }
    }
    $candidates = @()
    foreach ($root in $env:ProgramFiles, ${env:ProgramFiles(x86)}) {
        if (-not $root) { continue }
        $candidates += Join-Path $root 'GnuPG\bin\gpg.exe'
        $candidates += Join-Path $root 'Git\usr\bin\gpg.exe'
    }
    foreach ($c in $candidates) {
        if (Test-Path -LiteralPath $c -PathType Leaf) { return (Resolve-Path -LiteralPath $c).Path }
    }
    return $null
}

$script:Gpg = $null
$script:GpgIsMsys = $false

function Initialize-Gpg {
    $script:Gpg = Find-Gpg
    if (-not $script:Gpg) {
        Write-Note 'gpg is not installed, and it is needed to check the signature on the'
        Write-Note 'binary before running it. Install it and run this again:'
        Write-Note ''
        Write-Note '    winget install GnuPG.Gpg4win'
        exit 1
    }
    # An MSYS gpg reports its home directory as a POSIX path.
    $version = Invoke-Gpg @('--version')
    $script:GpgIsMsys = [bool]($version.Output | Where-Object { $_ -match '^Home: /' })
}

# ConvertTo-GpgPath renders a Windows path the way this gpg reads it. The MSYS
# build takes C:\x for a relative path and looks for it under the working
# directory; it reads /c/x.
function ConvertTo-GpgPath([string]$Path) {
    if (-not $script:GpgIsMsys) { return $Path }
    if ($Path -match '^([A-Za-z]):[\\/](.*)$') {
        return '/' + $Matches[1].ToLower() + '/' + ($Matches[2] -replace '\\', '/')
    }
    return ($Path -replace '\\', '/')
}

# Invoke-Gpg runs gpg and returns its exit code and output. Windows PowerShell
# turns a native program's stderr into terminating errors under 'Stop', which
# would abort on gpg's ordinary chatter, so the preference is relaxed here only.
function Invoke-Gpg([string[]]$Arguments) {
    $ErrorActionPreference = 'Continue'
    $output = & $script:Gpg @Arguments 2>$null
    return [pscustomobject]@{ Code = $LASTEXITCODE; Output = @($output) }
}

# --- verification ---------------------------------------------------------

# Verifies the detached signature and, separately, that the key which made it is
# the one pinned in this file. Verification alone would only establish that some
# key in the imported ring signed the file, which is not the question being
# asked. Returns $true when the file verifies against the pinned release key.
function Test-Signature([string]$File, [string]$Signature) {
    $key = Join-Path $BootstrapDir 'release-key.asc'
    if (-not (Test-Path -LiteralPath $Signature -PathType Leaf)) { return $false }
    if (-not (Test-Path -LiteralPath $key -PathType Leaf)) { return $false }
    if (-not $ReleaseKeyFingerprint) { return $false }

    $gpgHome = Join-Path ([System.IO.Path]::GetTempPath()) ('angou-gpg-' + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $gpgHome | Out-Null
    $saved = $env:GNUPGHOME
    $env:GNUPGHOME = ConvertTo-GpgPath $gpgHome
    try {
        # --no-autostart: importing a public key and checking a signature need
        # no gpg-agent, and starting one fails under Git for Windows' gpg when
        # the temporary directory's path is long, which turns a good import into
        # a non-zero exit. The import's exit code is not consulted for the same
        # reason; a key that did not import fails the verification below.
        $null = Invoke-Gpg @('--batch', '--quiet', '--no-autostart', '--import', (ConvertTo-GpgPath $key))
        $status = Join-Path $gpgHome 'status'
        $verified = Invoke-Gpg @('--batch', '--no-autostart', '--status-file', (ConvertTo-GpgPath $status),
            '--verify', (ConvertTo-GpgPath $Signature), (ConvertTo-GpgPath $File))
        if ($verified.Code -ne 0) { return $false }
        if (-not (Test-Path -LiteralPath $status)) { return $false }
        $pattern = 'VALIDSIG ' + $ReleaseKeyFingerprint
        return [bool](Select-String -LiteralPath $status -SimpleMatch -Pattern $pattern -Quiet)
    } finally {
        $env:GNUPGHOME = $saved
        Remove-Item -LiteralPath $gpgHome -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Assert-Binary([string]$Binary) {
    $name = Split-Path -Leaf $Binary
    $key = Join-Path $BootstrapDir 'release-key.asc'
    if (-not (Test-Path -LiteralPath "$Binary.sig" -PathType Leaf)) {
        Stop-Bootstrap "no signature beside $name; refusing to install it"
    }
    if (-not (Test-Path -LiteralPath $key -PathType Leaf)) {
        Stop-Bootstrap "no release-key.asc in $BootstrapDir; refusing to install an unverifiable binary"
    }
    if (-not $ReleaseKeyFingerprint) {
        Stop-Bootstrap 'this installer has no release key fingerprint pinned, so it cannot tell a genuine binary from a substituted one'
    }
    if (-not (Test-Signature $Binary "$Binary.sig")) {
        Stop-Bootstrap "$name is not signed by the release key this installer trusts ($ReleaseKeyFingerprint); refusing to install it"
    }
}

# --- main -----------------------------------------------------------------

if (-not (Test-Path -LiteralPath $BootstrapDir -PathType Container)) {
    Stop-Bootstrap "no bootstrap directory in $StoreDir; is this an angou store?"
}

$platform = Get-Platform
$binaryName = Get-Newest 'angou' $platform
if (-not $binaryName) {
    Write-Note "this store holds no binary for $($platform -replace '-', '/')."
    Write-Note 'available platforms:'
    Get-AvailablePlatforms | ForEach-Object { Write-Note "    $_" }
    exit 1
}
$binary = Join-Path $BootstrapDir $binaryName

Initialize-Gpg
# No passphrase is asked for here and none is needed: the binary is not
# encrypted. Only its signature is checked.
Assert-Binary $binary

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Copy-Item -LiteralPath $binary -Destination (Join-Path $InstallDir 'angou.exe') -Force
Write-Note "installed $binaryName to $(Join-Path $InstallDir 'angou.exe')"

# The desktop GUI, when the store carries one for this platform.
#
# Strictly a bonus. Recovery is the CLI's job and has already happened by this
# point, so a store with no GUI for this platform is the normal case, not an
# error. The GUI is verified to the same standard as the CLI: a binary
# installed from a store is a binary that will run on this machine, and being
# optional does not make it exempt.
$guiName = Get-Newest 'angou-gui' $platform
if ($guiName) {
    $gui = Join-Path $BootstrapDir $guiName
    Assert-Binary $gui
    $guiTarget = Join-Path $InstallDir 'angou-gui.exe'
    Copy-Item -LiteralPath $gui -Destination $guiTarget -Force
    Write-Note "installed $guiName to $guiTarget"

    # A Start menu entry, so the GUI is launchable from a menu rather than only
    # by name. Best effort: a machine where the shell cannot make one still has
    # the binary.
    try {
        $programs = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'
        New-Item -ItemType Directory -Force -Path $programs | Out-Null
        $link = Join-Path $programs 'angou.lnk'
        $shortcut = (New-Object -ComObject WScript.Shell).CreateShortcut($link)
        $shortcut.TargetPath = $guiTarget
        $shortcut.Description = 'Encrypt sensitive files into a portable, syncable store'
        $shortcut.Save()
        Write-Note "added a Start menu entry at $link"
    } catch {
        Write-Note "could not add a Start menu entry: $($_.Exception.Message)"
    }
} else {
    Write-Note "this store carries no desktop GUI for $($platform -replace '-', '/'); the CLI does everything it does"
}

# The PATH this process inherited is a snapshot. A directory added to the saved
# user or machine PATH since this terminal opened is not in it, and saying "not
# on your PATH" then sends the user to add it a second time.
function Test-OnPath([string]$PathList) {
    [bool](($PathList -split ';') | Where-Object { $_ -and ($_.TrimEnd('\') -ieq $InstallDir.TrimEnd('\')) })
}
$saved = [Environment]::GetEnvironmentVariable('Path', 'User') + ';' +
    [Environment]::GetEnvironmentVariable('Path', 'Machine')
if (-not (Test-OnPath $env:Path)) {
    if (Test-OnPath $saved) {
        Write-Note "$InstallDir is on your PATH from the next terminal you open; this one predates it."
    } else {
        Write-Note "warning: $InstallDir is not on your PATH; add it to run angou by name:"
        Write-Note "    [Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path', 'User') + ';$InstallDir', 'User')"
    }
}

# Post-install self-check (R5.8.2).
#
# This verifies this script against its own detached signature, made by the same
# offline release key that signed the binary. It cannot use the digest recorded
# inside the store: that record is encrypted, reading it needs the recovery
# passphrase, and nothing should ask for a passphrase at this point.
#
# It is detection after execution, not prevention. A deliberately subverted
# script would simply delete these lines, and this one has already run by the
# time you read its result. What it catches is a script that was altered without
# the release key: accidental drift from a sync conflict or a truncated file, and
# tampering by anyone who has write access to the store but not the offline key.
$self = $PSCommandPath
if (Test-Path -LiteralPath "$self.sig" -PathType Leaf) {
    if (Test-Signature $self "$self.sig") {
        Write-Note 'this installer matches its signature.'
    } else {
        Write-Note ''
        Write-Note 'WARNING: this installer does not match its signature.'
        Write-Note 'WARNING: this check ran after the installer did, so it does not tell you the'
        Write-Note 'WARNING: script you just ran was genuine. It tells you something changed.'
        Write-Note 'WARNING: Treat this machine as suspect and check the script against the'
        Write-Note 'WARNING: published repository before trusting it.'
        exit 1
    }
} else {
    Write-Note 'note: this installer carries no signature, so it could not be self-checked.'
}

Write-Note ''
# This script cannot tell a first install from an upgrade: knowing whether this
# machine already opens the store means reading the store, which it never does.
Write-Note "If this machine is new to the store, next: angou bootstrap --store `"$StoreDir`""
Write-Note 'That asks for your recovery passphrase and sets this machine up to open the store.'
Write-Note 'If it already opens the store, this was an upgrade and there is nothing more to do.'
exit 0
